import { FormEvent, useState } from "react";
import { ArrowLeft, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default function AdminLogin() { const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); const { data, error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError || !data.user) { setError(signInError?.message || "Unable to sign in"); setLoading(false); return; } const { data: isAdmin, error: roleError } = await supabase.rpc("has_role", { _user_id: data.user.id, _role: "admin" }); if (roleError || !isAdmin) { await supabase.auth.signOut(); setError("This account does not have administrator access."); setLoading(false); return; } navigate("/admin"); }; return <div className="flex min-h-screen items-center justify-center bg-[#080e19] px-5 text-slate-100"><Card className="w-full max-w-md border-slate-800 bg-slate-900/80 p-7 shadow-2xl"><Link to="/" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-white"><ArrowLeft className="h-4 w-4" />Back to KovaWealth</Link><div className="mt-8 flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><ShieldCheck className="h-6 w-6" /></div><h1 className="mt-5 text-2xl font-semibold text-white">Admin sign in</h1><p className="mt-2 text-sm leading-6 text-slate-500">Sign in with an approved administrator account to manage users and wallets.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm text-slate-300">Email address<Input required type="email" value={email} onChange={event => setEmail(event.target.value)} className="mt-2 h-11 border-slate-700 bg-slate-950 text-white" placeholder="admin@example.com" /></label><label className="block text-sm text-slate-300">Password<Input required type="password" value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-11 border-slate-700 bg-slate-950 text-white" placeholder="Your password" /></label>{error && <p className="text-sm text-red-300">{error}</p>}<Button disabled={loading} className="h-11 w-full bg-cyan-400 font-semibold text-slate-950 hover:bg-cyan-300"><LockKeyhole className="h-4 w-4" />{loading ? "Verifying..." : "Sign in securely"}</Button></form></Card></div>; }
